/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jrjs_ndkopencvtest_OpencvNativeClass */

#include <opencv2/opencv.hpp>

using namespace std;
using namespace cv;

// cabeceras de mis metodos
void Calibration(Rect currentFace);
int toGray(Mat img, Mat &gray);
int detect(Mat &frame, int size);
int getIndex(int size, Rect calibration, int xFaceCenter);

// variables globales
bool calibrated = false;
Rect calibration;

// lo que devuelve el metodo faceDetection
int xCentroCara = -1;


#ifndef _Included_com_example_jrjs_ndkopencvtest_OpencvNativeClass
#define _Included_com_example_jrjs_ndkopencvtest_OpencvNativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jrjs_ndkopencvtest_OpencvNativeClass
 * Method:    convertGray
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_example_jrjs_ndkopencvtest_OpencvNativeClass_convertGray
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_example_jrjs_ndkopencvtest_OpencvNativeClass
 * Method:    faceDetection
 * Signature: (JJLjava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_example_jrjs_ndkopencvtest_OpencvNativeClass_faceDetection
  (JNIEnv *, jclass, jlong, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
