/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jrjs_ndkopencvtest_OpencvNativeClass */

#include "headers.h"

#ifndef _Included_com_example_jrjs_ndkopencvtest_OpencvNativeClass
#define _Included_com_example_jrjs_ndkopencvtest_OpencvNativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jrjs_ndkopencvtest_OpencvNativeClass
 * Method:    smileDetection
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_example_jrjs_ndkopencvtest_OpencvNativeClass_smileDetection
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_jrjs_ndkopencvtest_OpencvNativeClass
 * Method:    getIndex
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_com_example_jrjs_ndkopencvtest_OpencvNativeClass_getIndex
        (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_example_jrjs_ndkopencvtest_OpencvNativeClass
 * Method:    eyeDetection
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_example_jrjs_ndkopencvtest_OpencvNativeClass_eyeDetection
        (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
